### ISSUE TITLE
How was the annotations example done?

### ISSUE THREAD

**Issue by Iainmon** [ruivieira/matplotcr#2]
I really love that you made a matplotlib interface for crystal! How were you able to change the fonts for the annotations example? Are you able to have different fonts for different things?

**Comment by ruivieira** [comment]
Hi @Iainmon, thanks!

That plot's source is here: https://github.com/ruivieira/matplotcr/blob/03b0bd5a5e3062f8896e02bbb6678d06c62f5a7c/spec/plots_spec.cr#L119

You can have different fonts, sure. Check https://github.com/ruivieira/matplotcr/blob/03b0bd5a5e3062f8896e02bbb6678d06c62f5a7c/src/matplotcr.cr#L26
